name: NS_BINDING_ABORTED bug in Playwright

on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    - run: npm ci
    - run: npx playwright install --with-deps
    - run: npm test
